### ISSUE TITLE
[Priority: High] Action Page - Functional Requirements

### ISSUE THREAD

**Issue by maobingjin** [soundpostgit/bem#15]
Action Page should tell user the following contents:
1. Which action I am taking, e.g. label/title for "Create Product'
2. Action on which object, e.g. item id 'Apple'
3. What is the object details, e.g display a list of attributes for user to fill out.
4. How to conclude the action now, including Cancel, Save, Save/Close, and Submit

**Comment by patricksiusee** [comment]
Jack, the design meeting the requirements is as follow. The idea is still data-driven while keeping the effort to minimum.

1. Title area (left aligned: Company banner, right aligned with 2 lines: L1 - <user id> signed in as <role> L2 - <action label> - <product_id>

2. The main body of the content pane:
     - multiple lines and one line for each attribute
     - the lines are organized in 2-column layout
     - left column as the attribute label and right column as the value
     - left and right column in the ratio 1:3 across the width of the content pane

3. The footer section of the content pane contains the 4 action buttons.
     - Submit
     - Save
     - Done Editing
     - Cancel

**Comment by patricksiusee** [comment]
Somehow the use of angle brackets were treated as markups and point #1 was cut off. Here's the full content.

1. Title area
      - left aligned: Company banner
      - right aligned with 2 lines
            - L1: [user_id] signed in as [role]
            - L2: [action_label] - [object_pk]

2. The main body of the content pane:
      - multiple lines and one line for each attribute
      - the lines are organized in 2-column layout
      - left column as the attribute label and right column as the value
      - left and right column in the ratio 1:3 across the width of the content pane

3. The footer section of the content pane contains the 4 action buttons.
      - Submit
      - Save
      - Done Editing
      - Cancel

**Comment by soundpostgit** [comment]
implemented this function via the following three commits:
https://github.com/soundpostgit/bem/commit/61260774dc93b73d81ddb5fd6ffcc3f2c5ef31ab

https://github.com/soundpostgit/bem/commit/44cee6097c63e846c77f19c2531b1051ec139434

https://github.com/soundpostgit/bem/commit/9ede7450f68b3e62da8bdb6b474e979fd99dafc6
