### ISSUE TITLE
bower component version conflicts

### ISSUE THREAD

**Issue by soundpostgit** [soundpostgit/bem#3]
bower install results in the following version conflict among bower components:

Unable to find a suitable version for angular, please choose one:
    1) angular#~1.4.7 which resolved to 1.4.9 and is required by angular-tooltips#1.0.7
    2) angular#1.5.0 which resolved to 1.5.0 and is required by angular-cookies#1.5.0, angular-mocks#1.5.0, angular-route#1.5.0
    3) angular#^1.0.8 which resolved to 1.5.0 and is required by angular-ui-router, angular-ui-router#0.2.18
    4) angular#^1.0.0 which resolved to 1.5.0 and is required by angular-smart-table#2.1.7

**Comment by patricksiusee** [comment]
Conflicts are not unusual. Their occurrences do not necessary mean issues.
Given we have not experience any runtime issues, I am closing out this issue.
